### ISSUE TITLE
[CHECKLIST] Integrate TSS creation flows into Tangle dApp

### ISSUE THREAD

**Issue by drewstone** [tangle-network/dapp#2055]
# Overview
We have the TSS UI flows from the zk-explorer app. They should be integrated into the Tangle dApp. This task is 2-fold

### Tasks
- [ ] webb-tools/webb-dapp#2069
- [ ] webb-tools/webb-dapp#2068
- [ ] Integrate the logic into the SDK.
- [ ] Test + document the logic in the SDK

### Linked
- https://github.com/webb-tools/webb-experiences/issues/246
- webb-tools/tangle-mpc-sdk#1
