### ISSUE TITLE
[CHECKLIST] Backend Integration for Service Overview Page

### ISSUE THREAD

**Issue by vutuanlinh2k2** [tangle-network/dapp#2286]
### Details
- [ ] Backend Integration for Service/Blueprint Distribution Chart on Service Overview Page
- [ ] Backend Integration for Protocol Earnings Chart on Service Overview Page
- [ ] Backend Integration for Service Stats on Service Overview Page
- [x] #2287

![Image](https://github.com/webb-tools/webb-dapp/assets/69841784/88c0db73-02cf-4d5c-9c46-141a168f14c7)
